title: Anderson Forestal githubProjects
first_name: Anderson
last_name: Forestal
email: feurintz86@gmail.com
fouter_text: >
powered by <a href="https://www.jekyllrb.com/" target="_blank">jekyll<a/> with >a href="
lang: en
url: https://wwww.githubProjects.io
theme: jekyll-theme-architect
show_downloads: false
google_analytics: "GTM-PTHS2KL"
description: [Description: Feel free to bookmark this to keep an eye on my project updates]
